/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/fox_walk.glb ./src/components/Fox2.jsx 
Author: tiikeri (https://sketchfab.com/tiikeri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fox-walk-3883b063fa004210a72198f7dd9bfec7
Title: Fox Walk
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Fox_walk({ animation, ...props }) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/models/fox_walk.glb");
  const { actions } = useAnimations(animations, group);
  console.log(actions);
  useEffect(() => {
    actions[animation]?.reset().fadeIn(0.24).play();
    return () => actions?.[animation]?.fadeOut(0.24);
  }, [animation]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="3a258e63cad643bf97c5250d8d764f15fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature002">
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group
                      name="Object_44"
                      position={[-10.064, 0.443, -2.831]}
                      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                    />
                    <skinnedMesh
                      name="Object_45"
                      geometry={nodes.Object_45.geometry}
                      material={materials.BrownFur}
                      skeleton={nodes.Object_45.skeleton}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_46"
                      geometry={nodes.Object_46.geometry}
                      material={materials.RedFur}
                      skeleton={nodes.Object_46.skeleton}
                      castShadow
                      receiveShadow
                    />
                    <skinnedMesh
                      name="Object_47"
                      geometry={nodes.Object_47.geometry}
                      material={materials.WhiteFur}
                      skeleton={nodes.Object_47.skeleton}
                      castShadow
                      receiveShadows
                    />
                  </group>
                </group>
                <group
                  name="Fox_Copy002"
                  position={[-10.064, 0.443, -2.831]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/fox_walk.glb");
